### ISSUE TITLE
Cola de procesamiento no actualiza el estado de las previsualizaciones

### ISSUE THREAD

**Issue by Madh93** [tic-ull/dpCat#21]
La cola de procesamiento puede gestionar hasta 5 procesos.

A la hora de procesar el vídeo de una nueva producción, una de las tareas que se deben en ejecutar es la de generar la previsualización. Las tareas de la cola pasan por 4 posibles estados:
- PEN (Pendiente)
- PRO (Procesando)
- HEC (Hecho)
- ERR (Error)

Se genera correctamente la previsualización. Sin embargo, el **estado de la tarea se mantiene en 'PRO' en vez de pasar a 'HEC'.** Esto hace que no se libere un slot de la cola de procesamiento, impidiendo así el procesamiento de nuevos videos una vez se hayan acumulado los 5 procesos.

**Comment by pchinea** [comment]
Si no me equivoco la cuestión no es que no se actualice el estado de la tarea (que se hace en [`proccess_task`](https://github.com/tic-ull/dpCat/blob/master/postproduccion/queue.py#L101)) sino que proceso está en el [bucle de los join](https://github.com/tic-ull/dpCat/blob/master/postproduccion/management/commands/procesar_video.py#L24) y hasta que no terminen el resto de tareas no continúa el bucle principal para procesar más.

**Comment by Madh93** [comment]
Al final el problema está [aquí](https://github.com/tic-ull/dpCat/blob/master/postproduccion/queue.py#L91).

Al no estar configurado el correo en local, se produce un fallo y el estado no se llega a actualizar.

**Comment by Madh93** [comment]
Arreglado para trabajar en local 285c72c
